<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Policy Acknowledgment Receipt</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; color: #333; line-height: 1.6; }
        .header { text-align: center; margin-bottom: 50px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .company-name { font-size: 24px; font-weight: bold; color: #1a237e; }
        .receipt-title { font-size: 18px; color: #666; margin-top: 10px; }
        .content { margin-bottom: 40px; }
        .detail-row { margin-bottom: 15px; }
        .label { font-weight: bold; width: 150px; display: inline-block; color: #555; }
        .value { color: #000; }
        .signature-box { margin-top: 60px; padding: 30px; border: 2px dashed #ccc; background-color: #f9f9f9; text-align: center; }
        .signature-title { font-weight: bold; margin-bottom: 10px; font-size: 16px; color: #1a237e; }
        .signature-text { font-family: 'Courier', monospace; font-size: 14px; margin-bottom: 5px; }
        .hash { font-size: 10px; color: #999; margin-top: 20px; word-break: break-all; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #aaa; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">HITECH GROUP</div>
        <div class="receipt-title">Certificate of Policy Acknowledgment</div>
    </div>

    <div class="content">
        <p>This document serves as formal confirmation that the employee named below has read, understood, and agreed to comply with the specified company policy.</p>

        <div class="detail-row">
            <span class="label">Employee Name:</span>
            <span class="value">{{ $userName }}</span>
        </div>
        <div class="detail-row">
            <span class="label">Employee Code:</span>
            <span class="value">{{ $user->employee_code ?? 'N/A' }}</span>
        </div>
        <div class="detail-row">
            <span class="label">Policy Title:</span>
            <span class="value">{{ $policy->title }}</span>
        </div>
        <div class="detail-row">
            <span class="label">Category:</span>
            <span class="value">{{ $policy->category }}</span>
        </div>
        <div class="detail-row">
            <span class="label">Acknowledged At:</span>
            <span class="value">{{ $acknowledged_at->format('F d, Y - h:i A') }}</span>
        </div>
        <div class="detail-row">
            <span class="label">IP Address:</span>
            <span class="value">{{ $ip_address }}</span>
        </div>
    </div>

    <div class="signature-box">
        <div class="signature-title">DIGITALLY SIGNED & VERIFIED</div>
        <div class="signature-text">E-Signed by: {{ $userName }}</div>
        <div class="signature-text">Verification ID: {{ strtoupper(substr($signature_hash, 0, 12)) }}</div>
        
        <div class="hash">
            Digital Fingerprint (SHA-256):<br>
            {{ $signature_hash }}
        </div>
    </div>

    <div class="footer">
        This is a system-generated document. No physical signature is required. 
        Generated by Hitech HRX Management System on {{ now()->format('Y-m-d H:i:s') }}
    </div>
</body>
</html>
