<?php
// Variables
return [
  "creatorName" => "Nerds",
  "creatorUrl" => "https://hitechgroup.in/",
  "supportNumber" => "+91 9814215000",
  "supportWhatsappURL" => "https://wa.me/+919814215000",
  "supportEmail" => "info@hitechgroup.in",
  "templateName" => "Hi Tech HRX",
  "templateFullName" => "Hi Tech HRX",
  "templateSuffix" => "",
  "templateVersion" => "4.2.1",
  "templateFree" => false,
  "templateDescription" => "AI-Driven HRMS for Modern Businesses.",
  "templateLicense" => "HRX Commercial License",
  "licenseUrl" => "https://hitechgroup.in/license/",
  "livePreview" => "https://hrx.hitechgroup.in",
  "productPage" => "https://hitechgroup.in",
  "support" => "https://hitechgroup.in/contact-us/",
  "activationDocs" => "https://hitechgroup.in/",
  "moreThemes" => "https://hitechgroup.in",
  "documentation" => "https://hitechgroup.in",
  "changelog" => "https://hitechgroup.in",
  "repository" => "https://hitechgroup.in",
  "gitRepo" => "https://hitechgroup.in",
  "gitRepoAccess" => "https://hitechgroup.in",
  "githubFreeUrl" => "https://hitechgroup.in",
  "facebookUrl" => "https://hitechgroup.in",
  "twitterUrl" => "https://hitechgroup.in",
  "githubUrl" => "https://hitechgroup.in",
  "dribbbleUrl" => "https://hitechgroup.in",
  "instagramUrl" => "https://www.instagram.com/hitechhrx/",
  'linkedInUrl' => 'https://www.linkedin.com/company/hitechgroup',
  'youtubeUrl' => 'https://www.youtube.com/@hitechgroup',
  'appDemoLink' => 'https://drive.google.com/file/d/1YtgotCgi70DF3xjK4qAlCdkZP3KyDp9E/view?usp=sharing',
  'superAdminPanelDemoLink' => 'https://hrx.hitechgroup.in/',
  'adminPanelDemoLink' => 'https://hrx.hitechgroup.in/',
  'itemId' => 8849,
  'envatoItemId' => 50190332,
];
